name: "check permission action"
description: >
  A GitHub Action to check workflow permissions.

inputs:
  github-token:
    description: "Token to call GitHub API"
    required: false
    default: ${{ github.token }}

outputs:
  pull-request:
    description: >
      permission on pull requests
      This will be `write` or `read` or `none`.
    value: ${{ steps.check-permission.outputs.pull-request }}

runs:
  using: "composite"
  steps:
    - name: setup deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: run action
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: deno run --quiet --allow-all main.ts