name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: none
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: fail to view PR
        run: gh pr view 1
      - name: test
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}